### ISSUE TITLE
Superclasses on foreign-vector are in the wrong order 

### ISSUE THREAD

**Issue by Yehouda** [Shirakumo/cl-fbx#1]
https://github.com/Shirakumo/cl-fbx/blob/dd66aacdecf1d61ee0fdc8909470bac2d79a04d9/wrapper.lisp#L90

Putting **standard-object** before **seqeunces:sequence** means that in the precedence list **standard-object** needs to precede **seqeunces:sequence**, but  **seqeunces:sequence** have to precede  **standard-object**  because it is its superclass.  (second paragraph in 
[4.3.5 Determining the Class Precedence List](http://www.lispworks.com/documentation/lw50/CLHS/Body/04_ce.htm)), so this is inconsistent.

Is there a reason to have **standard-object** in the superclasses list?

**Comment by Shinmera** [comment]
`sequence` is not guaranteed to be a `standard-object`. On SBCL notably it is not.

**Comment by Yehouda** [comment]
Ok, but the order still needs to be fixed for other implementations.
